### ISSUE TITLE
改为闭源后网易云无法联网

### ISSUE THREAD

**Issue by MillerShan** [ReviveUnblockNCMInstaller/RevivedUnblockInstaller#10]

**Comment by wldll** [comment]
![屏幕截图 2023-05-07 214426](https://user-images.githubusercontent.com/45764738/236681290-3d1837f5-96fc-4351-89a0-af6c02cde762.png)
把http代理改成不使用代理试试

**Comment by anpoz** [comment]
实测把插件禁用以及设置不使用代理，本体也无法联网了，蹲一个解决办法

**Comment by Eachann13** [comment]
> ![屏幕截图 2023-05-07 214426](https://user-images.githubusercontent.com/45764738/236681290-3d1837f5-96fc-4351-89a0-af6c02cde762.png) 把http代理改成不使用代理试试

我这边试了有效，可以联网，如果插件商店加载不出来可以把插件源改成Gitee

**Comment by anpoz** [comment]
发现问题了，插件自动把hosts文件改了，而禁用插件的时候没有改回去，导致无法联网
![image](https://github.com/ReviveUnblockNCMInstaller/RevivedUnblockInstaller/assets/2825342/0c045d0b-664d-4193-8b80-365c545f86f9)

**Comment by ReviveUnblockNCMInstaller** [comment]
> 发现问题了，插件自动把hosts文件改了，而禁用插件的时候没有改回去，导致无法联网 ![image](https://user-images.githubusercontent.com/2825342/237595291-0c045d0b-664d-4193-8b80-365c545f86f9.png)

本插件以及 https://github.com/UnblockNeteaseMusic/server 不会修改 hosts，大概是你自己安装了另一个 Go 版本的
