### ISSUE TITLE
安装BetterNCM后，根据安装步骤，但是点击自定义后没有反应怎么解决呀

### ISSUE THREAD

**Issue by niguangerlai** [ReviveUnblockNCMInstaller/RevivedUnblockInstaller#11]
如题

**Comment by Pinghigh** [comment]
仔细阅读 readme，原作者把自定义关了

**Comment by KKKKKKKKK66666666** [comment]
解不了灰了 我的杰伦555

**Comment by zhaocai** [comment]
可以自己下载[RevivedUnblockNeteaseMusic.plugin](https://github.com/ReviveUnblockNCMInstaller/RevivedUnblockInstaller/blob/close/RevivedUnblockNeteaseMusic.plugin)文件，拷贝到BetterNCM的plugins目录。

**Comment by lucifer714** [comment]
装好BetterNCM之后，点击 `打开插件文件夹` ，把下载的插件丢到 `C:\betterncm\plugins` 中,重启即可。

![Snipaste_2023-06-05_11-06-02](https://picdl.sunbangyan.cn/2023/06/05/icefkr.png)

**Comment by 1106458351** [comment]
> 装好BetterNCM之后，点击 `打开插件文件夹` ，把下载的插件丢到 `C:\betterncm\plugins` 中,重启即可。
> 
> ![Snipaste_2023-06-05_11-06-02](https://private-user-images.githubusercontent.com/10623252/243242798-4eb8609f-9832-4baf-b2db-30a1a4fcb59d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0NzU4ODIsIm5iZiI6MTcxNzQ3NTU4MiwicGF0aCI6Ii8xMDYyMzI1Mi8yNDMyNDI3OTgtNGViODYwOWYtOTgzMi00YmFmLWIyZGItMzBhMWE0ZmNiNTlkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA0VDA0MzMwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlhMzZiZjYzYmEwZDI4MjY3YThlYjVjMTNjZTI1MzI0MjUxYmQyMWY3MmRjOWI1YjVkNzMxYjgyYjE3NWY4YmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FdUJMxXzXhlQ3EIHJf5wunOUlHcEGaKU1PeaRbjCCQw)

向您致敬，之前一直被困在加载界面
