### ISSUE TITLE
第一次无法正常下载，第二次下载成功，但无用且删除之后，后续下载重启软件之后无法正常下载。

### ISSUE THREAD

**Issue by Tinjues** [ReviveUnblockNCMInstaller/RevivedUnblockInstaller#14]
第一次下载下载成功，显示下载成功重启软件后 **显示下载按钮（需重新下载）**。
第二次下载下载成功，显示下载成功重启软件后 **无法显示BetterNCM 插件列表空白且打开RevivedUnblockInstaller设置空白（无界面，无文字）**  第二次下载删除之后BetterNCM正常。
第三次下载下载成功，显示下载成功重启软件后 **显示下载按钮（需重新下载）**。
第四次·····
第五次····
后续下载都不能下载下来RevivedUnblockInstaller，且成功下载却无法使用的问题。

**Comment by JXing233** [comment]
同样的问题，安装完成之后显示需要重载，点击重载后，显示的还是安装，并没有成功安装上

**Comment by JXing233** [comment]
> 同样的问题，安装完成之后显示需要重载，点击重载后，显示的还是安装，并没有成功安装上
在已安装的插件列表里能看见插件已经安装，点击没有任何东西，插件商店任然显示没有安装

**Comment by Tinjues** [comment]
> > 同样的问题，安装完成之后显示需要重载，点击重载后，显示的还是安装，并没有成功安装上
> > 在已安装的插件列表里能看见插件已经安装，点击没有任何东西，插件商店任然显示没有安装

  她好像闭源了。但是我不知道BetterNCM为什么还会上她的解灰。

**Comment by Tinjues** [comment]
> > > 同样的问题，安装完成之后显示需要重载，点击重载后，显示的还是安装，并没有成功安装上
> > > 在已安装的插件列表里能看见插件已经安装，点击没有任何东西，插件商店任然显示没有安装
> 
> 她好像闭源了。但是我不知道BetterNCM为什么还会上她的解灰。

**Comment by ReviveUnblockNCMInstaller** [comment]
检查 C:\betterncm\UnblockCloudMusic 内是否有服务器文件。
