### ISSUE TITLE
歌曲匹配错误的重新定向问题

### ISSUE THREAD

**Issue by Maozai-Teng** [ReviveUnblockNCMInstaller/RevivedUnblockInstaller#15]
如果歌曲默认的匹配错了，我应该怎么样自定义重新选择呢？
没有找到任何相关设置的地方，能否指点一二，谢谢了
比如这首歌，https://music.163.com/#/song?id=526464747& 默认出来的音乐和歌曲对不上（好像是同一个歌手，但歌曲对不上）
再次感谢~

**Comment by ReviveUnblockNCMInstaller** [comment]
还没做
