### ISSUE TITLE
[申请入源] RevivedNcmDump

### ISSUE THREAD

**Issue by GADDQ** [ReviveUnblockNCMInstaller/RevivedUnblockInstaller#18]
https://github.com/ReviveUnblockNCMInstaller/RevivedSource/issues/2

**Comment by ReviveUnblockNCMInstaller** [comment]
你需要自行将其打包为 .plugin 格式并放入 repo 中

**Comment by GADDQ** [comment]
我该怎么把插件放入repo呢
cdn上没有上传文件的选项

**Comment by GADDQ** [comment]
https://github.com/ReviveUnblockNCMInstaller/RevivedUnblockInstaller/pull/19
这样可以了吗？
