### ISSUE TITLE
没有对应版本可以选择

### ISSUE THREAD

**Issue by LinJie-mjyb** [ReviveUnblockNCMInstaller/RevivedUnblockInstaller#2]
![image](https://user-images.githubusercontent.com/74543319/230772130-df427fed-731d-4bbd-b877-daedd194ac99.png)
下载插件之后就一直都是这样，没有可下载的版本

**Comment by Yahoo94** [comment]
+1

**Comment by ReviveUnblockNCMInstaller** [comment]
可能是没有成功请求到 Github API，尝试重载。
