### ISSUE TITLE
开启后没有下载选项

### ISSUE THREAD

**Issue by RunzZli** [ReviveUnblockNCMInstaller/RevivedUnblockInstaller#20]
![d72e54972772be9479ee8c5d8082023](https://github.com/ReviveUnblockNCMInstaller/RevivedUnblockInstaller/assets/122367951/e3ac0fd4-b3c8-4e6d-b457-1db4167b8707)

**Comment by ReviveUnblockNCMInstaller** [comment]
网络问题。
