### ISSUE TITLE
一直显示启动服务中，无法正常启用，提示选择版本，但是要启用后才能选用不是吗？

### ISSUE THREAD

**Issue by BackQ1** [ReviveUnblockNCMInstaller/RevivedUnblockInstaller#21]
![QQ图片20230907102713](https://github.com/ReviveUnblockNCMInstaller/RevivedUnblockInstaller/assets/144299141/925b3d5a-134b-44ab-8a07-8e1726be4f66)
![QQ图片20230907102709](https://github.com/ReviveUnblockNCMInstaller/RevivedUnblockInstaller/assets/144299141/a63490c4-dd4a-48b9-af18-f907f63a6d30)

**Comment by BackQ1** [comment]
![1](https://github.com/ReviveUnblockNCMInstaller/RevivedUnblockInstaller/assets/144299141/0db2fed5-0081-4a22-80a1-7a0e80d1ad07)

**Comment by BackQ1** [comment]
解决了，通过环境变量把betterncm的文件位置都设置为C盘根目录文件就可以了

**Comment by sillyru** [comment]
> 解决了，通过环境变量把beterncm的文件位置都设置为C盘根目录文件就可以了

请问怎么操作？我也是和你一样的提示。我beterncm的文件夹位置就是在c盘根目录的。是因为我网易云装在d盘吗？

**Comment by BackQ1** [comment]
> > 解决了,通过环境变量把beterncm的文件位置都设置为C盘根目录文件就可以了
> 
> 请问怎么操作？我也是和你一样的提示。我beterncm的文件夹位置就是在c盘根目录的。是因为我网易云装在d盘吗？

可能有这个原因，但不一定，你看看https://v2e2npdz15.feishu.cn/docx/UZkSd9d46o4fVOxaPNBcGXSenme这个教程里面环境变量。看看你的两个文件位置是不是一样的。我看的时候只有一个有，另一个空白的，我自己添加的。

**Comment by BackQ1** [comment]
> > > 解决了,通过环境变量把beterncm的文件位置都设置为C盘根目录文件就可以了
> > 
> > 
> > 请问怎么操作？我也是和你一样的提示。我beterncm的文件夹位置就是在c盘根目录的。是因为我网易云装在d盘吗？
> 
> 可能有这个原因,但不一定,你看看[https://v2 e 2 npdz 15 . Fei Shu . cn/docx/uzksd 9d 46 o 4 fvoxapnbcgxsenme这个教程里面环境变量。看看你的两个文件位置是不是一样的。我看的时候只有一个有,另一个空白的,我自己添加的。](https://v2e2npdz15.feishu.cn/docx/UZkSd9d46o4fVOxaPNBcGXSenme%E8%BF%99%E4%B8%AA%E6%95%99%E7%A8%8B%E9%87%8C%E9%9D%A2%E7%8E%AF%E5%A2%83%E5%8F%98%E9%87%8F%E3%80%82%E7%9C%8B%E7%9C%8B%E4%BD%A0%E7%9A%84%E4%B8%A4%E4%B8%AA%E6%96%87%E4%BB%B6%E4%BD%8D%E7%BD%AE%E6%98%AF%E4%B8%8D%E6%98%AF%E4%B8%80%E6%A0%B7%E7%9A%84%E3%80%82%E6%88%91%E7%9C%8B%E7%9A%84%E6%97%B6%E5%80%99%E5%8F%AA%E6%9C%89%E4%B8%80%E4%B8%AA%E6%9C%89%EF%BC%8C%E5%8F%A6%E4%B8%80%E4%B8%AA%E7%A9%BA%E7%99%BD%E7%9A%84%EF%BC%8C%E6%88%91%E8%87%AA%E5%B7%B1%E6%B7%BB%E5%8A%A0%E7%9A%84%E3%80%82)

[https://v2e2npdz15.feishu.cn/docx/UZkSd9d46o4fVOxaPNBcGXSenme](url)这个是教程链接

**Comment by xiaojieen** [comment]
解决了吗？我的也是这样，我在c盘啊

**Comment by KhashzM** [comment]
我的解决了，不知道你们的行不行
https://wwji.lanzouj.com/itMLb19l9ygb
文件下载后把解压出的文件放到Batterncm数据文件夹下的RevivedUnblockInstaller文件夹里

**Comment by Protein-V** [comment]
> 我的解决了，不知道你们的行不行 https://wwji.lanzouj.com/itMLb19l9ygb 文件下载后把解压出的文件放到Batterncm数据文件夹下的RevivedUnblockInstaller文件夹里

可以！！佬 阿里嘎多美羊羊桑

**Comment by Protein-V** [comment]
> > 我的解决了，不知道你们的行不行 https://wwji.lanzouj.com/itMLb19l9ygb 文件下载后把解压出的文件放到Batterncm数据文件夹下的RevivedUnblockInstaller文件夹里
> 
> 可以！！佬 阿里嘎多美羊羊桑

但是有个问题就是这个解锁服务启动后，BetterNCM的插件市场就一直加载不出来了，很懊恼，电脑开了全局系统代理的都，所有浏览器都轻松直通外网了，这个咋就是加载不出来呢/(ㄒoㄒ)/~~

**Comment by Protein-V** [comment]
> > > 我的解决了，不知道你们的行不行 https://wwji.lanzouj.com/itMLb19l9ygb 文件下载后把解压出的文件放到Batterncm数据文件夹下的RevivedUnblockInstaller文件夹里
> > 
> > 
> > 可以！！佬 阿里嘎多美羊羊桑
> 
> 但是有个问题就是这个解锁服务启动后，BetterNCM的插件市场就一直加载不出来了，很懊恼，电脑开了全局系统代理的都，所有浏览器都轻松直通外网了，这个咋就是加载不出来呢/(ㄒoㄒ)/~~

这个修改Hosts后解决了！
