### ISSUE TITLE
下载那里是空的，并没有什么版本选择

### ISSUE THREAD

**Issue by ssrubsd** [ReviveUnblockNCMInstaller/RevivedUnblockInstaller#22]
![image](https://github.com/ReviveUnblockNCMInstaller/RevivedUnblockInstaller/assets/59917319/faa6fbee-c113-49ff-88f1-74e57567a693)

已开启代理，所以应该不是网络问题

**Comment by zzzrzy2** [comment]
加一

**Comment by UPXiaoli** [comment]
同

**Comment by ReviveUnblockNCMInstaller** [comment]
网络问题。
