### ISSUE TITLE
按着教程操作,但一直显示启动服务失败。。。

### ISSUE THREAD

**Issue by 462051887** [ReviveUnblockNCMInstaller/RevivedUnblockInstaller#24]
![Snipaste_2023-10-02_01-39-17](https://github.com/ReviveUnblockNCMInstaller/RevivedUnblockInstaller/assets/69186626/5c1c6e0c-79ff-48db-9e3a-0c8c6e0df812)

**Comment by ReviveUnblockNCMInstaller** [comment]
什么教程？
