### ISSUE TITLE
使用QQ音源之后歌曲封面无法加载

### ISSUE THREAD

**Issue by oopb** [ReviveUnblockNCMInstaller/RevivedUnblockInstaller#26]
如题，在我将自己的uid以及key添加之后很长一段时间歌曲封面加载不出来，今天取消了qq音源以及网易云第三方api之后则恢复正常

**Comment by ReviveUnblockNCMInstaller** [comment]
请到 https://github.com/UnblockNeteaseMusic/server 上游报告此问题。
