### ISSUE TITLE
下载进度一直 0%

### ISSUE THREAD

**Issue by Protein-V** [ReviveUnblockNCMInstaller/RevivedUnblockInstaller#27]
网易版本 2.10.12 
![Snipaste_2023-11-10_21-37-49](https://github.com/ReviveUnblockNCMInstaller/RevivedUnblockInstaller/assets/132827369/353b4c02-c664-40cb-af8d-93b908790602)
代理  tun模式 - 规则-系统代理

**Comment by Protein-V** [comment]
我自认为我的代理是没啥问题的，油管4K秒开，但是装了RevivedUnblockInstaller插件，不但BetterNCM的插件市场加载不出来(顶掉了网易云当中的代理设置)，下载相应的解锁包也一直 0%，各给佬球球解！

**Comment by gulin1735958071** [comment]
我也是这样 人嘛了

**Comment by windbreaker299** [comment]
同样啊，求大佬解

**Comment by china-gulin** [comment]
我直接下载0.27.2去了

**Comment by windbreaker299** [comment]
0.27.2可以么？ 怎么下载这个版本呢 我好像没有0.27.2的选项

**Comment by china-gulin** [comment]
![image](https://github.com/ReviveUnblockNCMInstaller/RevivedUnblockInstaller/assets/111722031/e0479379-d5a1-46a4-90be-c2f171984bac)

**Comment by china-gulin** [comment]
![image](https://github.com/ReviveUnblockNCMInstaller/RevivedUnblockInstaller/assets/111722031/537871e9-2b58-499e-9cc8-b981db50a686)
我就只能用这唯一一个版本 剩下的我都用不了

**Comment by windbreaker299** [comment]
(https://github.com/ReviveUnblockNCMInstaller/RevivedUnblockInstaller/assets/48781833/4ae83739-13b8-4c45-96bf-bef2b49c2985)
为什么我只有这两个呢

**Comment by china-gulin** [comment]
> (https://github.com/ReviveUnblockNCMInstaller/RevivedUnblockInstaller/assets/48781833/4ae83739-13b8-4c45-96bf-bef2b49c2985） 为什么我只有这两个呢

你的网易云是啥版本
我是之前用的老版本然后就有这个0.27.2 然后升级后出现的0.27.4 我没用内测 我现在是2.10.12 我之前用的好像是2.10.02 我也记不太清楚了 我觉得你可以试试下载老版网易 然后看看会不会出现0.27.2 有的话再升级也可以吧 希望我的回答对你有帮助！

**Comment by windbreaker299** [comment]
> > ([https://github.com/ReviveUnblockNCMInstaller/RevivedUnblockInstaller/assets/48781833/4ae83739-13b8-4c45-96bf-bef2b49c2985）](https://github.com/ReviveUnblockNCMInstaller/RevivedUnblockInstaller/assets/48781833/4ae83739-13b8-4c45-96bf-bef2b49c2985%EF%BC%89) 为什么我只有这两个呢
> 
> 你的网易云是啥版本 我是之前用的老版本然后就有这个0.27.2 然后升级后出现的0.27.4 我没用内测 我现在是2.10.12 我之前用的好像是2.10.02 我也记不太清楚了 我觉得你可以试试下载老版网易 然后看看会不会出现0.27.2 有的话再升级也可以吧 希望我的回答对你有帮助！

我用的是2.10.12，只有两个选项，那我去找找老版本，谢谢你的回答，非常感谢

**Comment by Protein-V** [comment]
> 我自认为我的代理是没啥问题的，油管4K秒开，但是装了RevivedUnblockInstaller插件，不但BetterNCM的插件市场加载不出来(顶掉了网易云当中的代理设置)，下载相应的解锁包也一直 0%，各给佬球球解！

**Comment by Protein-V** [comment]
> 我自认为我的代理是没啥问题的，油管4K秒开，但是装了RevivedUnblockInstaller插件，不但BetterNCM的插件市场加载不出来(顶掉了网易云当中的代理设置)，下载相应的解锁包也一直 0%，各给佬球球解！

大家遇到这个问题的话可以看看这个议题的回复 https://github.com/ReviveUnblockNCMInstaller/RevivedUnblockInstaller/issues/21 
这里边有个友友分享了 https://wwji.lanzouj.com/itMLb19l9ygb
版本文件下载后把解压出的文件放到Batterncm数据文件夹下的RevivedUnblockInstaller文件夹里重启网易云即可解锁灰色地带啦
遇到插件市场加载不出来的情况可以尝试修改系统Hosts

**Comment by windbreaker299** [comment]
> > 我自认为我的代理是没啥问题的，油管4K秒开，但是装了RevivedUnblockInstaller插件，不但BetterNCM的插件市场加载不出来(顶掉了网易云当中的代理设置)，下载相应的解锁包也一直 0%，各给佬球球解！
> 
> 大家遇到这个问题的话可以看看这个议题的回复 #21 这里边有个友友分享了 https://wwji.lanzouj.com/itMLb19l9ygb 版本文件下载后把解压出的文件放到Batterncm数据文件夹下的RevivedUnblockInstaller文件夹里重启网易云即可解锁灰色地带啦 遇到插件市场加载不出来的情况可以尝试修改系统Hosts

可以，顺利解决了，非常感谢。

**Comment by windbreaker299** [comment]
Protein-V兄弟能教教我怎么填QQ音乐的cookie么？
