### ISSUE TITLE
下载进度卡在0%（已解决，方案在最底部）

### ISSUE THREAD

**Issue by BMYuri** [ReviveUnblockNCMInstaller/RevivedUnblockInstaller#28]
无法下载

**Comment by MTfriday** [comment]
遇到相同情况

**Comment by IGNiT3-R** [comment]
遇到相同情况

**Comment by YukimiNan** [comment]
选择ghproxy源，打开C:\betterncm\RevivedUnblockInstaller\config.json，把download_url的域名从ghproxy.com改为mirror.ghproxy.com

**Comment by Alossom** [comment]
> 选择ghproxy源，打开C:\betterncm\RevivedUnblockInstaller\config.json，把download_url的域名从ghproxy.com改为mirror.ghproxy.com

not working，依然卡在0%，挂了VPN也没用

**Comment by gankumangcao** [comment]
我也一样，你解决了吗

**Comment by Kaleidoscope39** [comment]
> 选择ghproxy源，打开C:\betterncm\RevivedUnblockInstaller\config.json，把download_url的域名从ghproxy.com改为mirror.ghproxy.com

在这个基础上把 `config.json` 设置为只读，然后重新进行下载就好了。如果反代ghproxy不可用换个别的就行。

**Comment by yechen2018** [comment]
打开C：\betterncm\RevivedUnblockInstaller\config.json 找到download_url而里面的内容是下载链接复制，前面的代理就不用复制了，去浏览器下载找个网盘上传，上传之后复制下载链接，返回config.json把里面的链接替换成你上传后的下载链接

**Comment by BMYuri** [comment]
模式选择ghprox
打开C：\betterncm\RevivedUnblockInstaller\config.json**
将配置文件中的下载地址复制下来浏览器下载
把下载到的文件改名为UnblockNeteaseMusic-v0.27.4-patch.1-ghproxy并拖至文件夹
应用

**Comment by BMYuri** [comment]
模式选择ghprox
打开C：\betterncm\RevivedUnblockInstaller\config.json**
将配置文件中的下载地址复制下来浏览器下载
把下载到的文件改名为UnblockNeteaseMusic-v0.27.4-patch.1-ghproxy并拖至文件夹
应用

**Comment by Subaiy** [comment]
> 模式选择ghprox 打开C：\betterncm\RevivedUnblockInstaller\config.json** 将配置文件中的下载地址复制下来浏览器下载 把下载到的文件改名为UnblockNeteaseMusic-v0.27.4-patch.1-ghproxy并拖至文件夹 应用

应该改成：“UnblockNeteaseMusic-v0.27.4-patch.1.exe“才对吧，我改你那个识别不出来

**Comment by CaseYwY** [comment]
服了，看了config半天，ghproxy这个网站被反诈封了，有魔法的直接选没有第一个。没有的就去https://github.com/UnblockNeteaseMusic/server/releases 下载最新版本，到C:\betterncm\RevivedUnblockInstaller\这个文件夹里
