### ISSUE TITLE
启动UnblockMusic服务失败

### ISSUE THREAD

**Issue by yukiryo** [ReviveUnblockNCMInstaller/RevivedUnblockInstaller#29]
![image](https://github.com/ReviveUnblockNCMInstaller/RevivedUnblockInstaller/assets/58250223/c9c419d8-6b7c-470d-accc-06437cccda74)

**Comment by TripleLLLV** [comment]
遇到相同情况 求解决方案

**Comment by dhicoc** [comment]
![image](https://github.com/ReviveUnblockNCMInstaller/RevivedUnblockInstaller/assets/94750419/25848374-a365-4c3f-a214-96657b20e565)

**Comment by dhicoc** [comment]
怎么解决

**Comment by HideUsSaveUs** [comment]
@ReviveUnblockNCMInstaller @MicroCBer
