### ISSUE TITLE
[Revived UnblockMusic]未连接网络

### ISSUE THREAD

**Issue by Cyberxxt** [ReviveUnblockNCMInstaller/RevivedUnblockInstaller#30]
本人在国外，实测插件通过WIFI无法连接。打开软件后提示“[Revived UnblockMusic]未连接网络”
但是连接流量可以正常使用。

**Comment by ReviveUnblockNCMInstaller** [comment]
本插件的网络连接检测是用的网易云自己的在无代理情况下的连接检测，如果显示连不上，就说明确实连不上。
