### ISSUE TITLE
虽然服务启动成功，但插件设置界面空白，没有任何设置选项

### ISSUE THREAD

**Issue by hosts765614407** [ReviveUnblockNCMInstaller/RevivedUnblockInstaller#36]
![1706068368030](https://github.com/ReviveUnblockNCMInstaller/RevivedUnblockInstaller/assets/23698177/a9bed95f-7463-496c-8aa0-dced823b3b76)

**Comment by WadeChaoCD** [comment]
同问题

**Comment by xingguangworld** [comment]
加一

**Comment by zhangaceof** [comment]
+1

**Comment by ReviveUnblockNCMInstaller** [comment]
可以 F12 在 Console 页截图看看吗？

**Comment by zhangaceof** [comment]
![{623545D3-228B-4d66-8F3B-8897D79B9C97}](https://github.com/ReviveUnblockNCMInstaller/RevivedUnblockInstaller/assets/40111336/cb03edca-cd80-4d07-8ac3-82c555b513ad)
![{D7424CCD-9650-46ed-AAC1-B2A7A82BB07B}](https://github.com/ReviveUnblockNCMInstaller/RevivedUnblockInstaller/assets/40111336/2135ffca-f807-4cb1-b09f-f1ce7d39f9f6)

**Comment by zhangaceof** [comment]
我可以开todesk 你看控制台   ToDesk:
设备代码:121 057 388
临时密码:840jmjh6

**Comment by zhangaceof** [comment]
![image](https://github.com/ReviveUnblockNCMInstaller/RevivedUnblockInstaller/assets/40111336/b833d395-99eb-46e8-bcd4-c6b13b2e2d0c)

**Comment by zhangaceof** [comment]
> ![image](https://private-user-images.githubusercontent.com/40111336/300250512-b833d395-99eb-46e8-bcd4-c6b13b2e2d0c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0MzMzNTIsIm5iZiI6MTcwNjQzMzA1MiwicGF0aCI6Ii80MDExMTMzNi8zMDAyNTA1MTItYjgzM2QzOTUtOTllYi00NmU4LWJjZDQtYzZiMTNiMmUyZDBjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI4VDA5MTA1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiMWQ4ZjgyODA4MjIwOTY1NTRmYTkwNmY4MTM0ZjQ2NTljMDdhNmJkNmM2MDYzYTg2NWEzYjdjZGE1ODNiMjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1tZuJ8vvNNuR4AnrqqbMuGdg4b3ujGpXBQwWsECjljg)

@ReviveUnblockNCMInstaller

**Comment by hosts765614407** [comment]
> 可以在控制台F12页截图看看吗？
![060c77ebb9b7d7c27fa7b94a5f54732](https://github.com/ReviveUnblockNCMInstaller/RevivedUnblockInstaller/assets/23698177/a3a87727-7ad4-4ab5-8c8d-02ae03ca590f)
![0f8dda0588ad311dcf0b455baf7bb8c](https://github.com/ReviveUnblockNCMInstaller/RevivedUnblockInstaller/assets/23698177/6b0ecc21-2634-4eb6-a6f4-27e01df7b3d6)
![1a5c6912c5dda9c1c611f0992ffdef0](https://github.com/ReviveUnblockNCMInstaller/RevivedUnblockInstaller/assets/23698177/77518bba-ae4b-422c-a6d2-3d24da893e42)
