### ISSUE TITLE
安装installer后无法正常启动服务，附详细信息，请求作者帮助

### ISSUE THREAD

**Issue by CapitalGrin** [ReviveUnblockNCMInstaller/RevivedUnblockInstaller#37]
安装installer后无法正常启动服务，显示未选择服务，且卡在启动界面，如下图
![image](https://github.com/ReviveUnblockNCMInstaller/RevivedUnblockInstaller/assets/109933411/7d879ada-7043-445d-a961-dfc67d4b4891)
重启后则表现为无设置项，也没有服务器进程被启动
![image](https://github.com/ReviveUnblockNCMInstaller/RevivedUnblockInstaller/assets/109933411/485eb29d-f863-4dbf-b5cd-16a502711a80)
自查 C:\betterncm\RevivedUnblockInstaller 内没有服务器文件，config文件内容可能异常，内容如下
`{"enabled":true,"upstream-proxy":"","netease-cookie":"","source-order":[{"name":"QQ 音乐","code":"qq","enable":true,"note":"需要准备自己的 QQ_COOKIE（请参阅下方〈环境变量〉处）。必须使用 QQ 登录。"},{"name":"酷狗音乐","code":"kugou","enable":true},{"name":"酷我音乐","code":"kuwo","enable":true},{"name":"咪咕音乐","code":"migu","enable":true,"note":"需要准备自己的 MIGU_COOKIE（请参阅下方〈环境变量〉处）。"},{"name":"JOOX","code":"joox","enable":false,"note":"需要准备自己的 JOOX_COOKIE（请参阅下方〈环境变量〉处）。似乎有严格地区限制。"},{"name":"YouTube（纯 JS 解析方式）","code":"youtube","enable":false,"note":"需要 Google 认定的非中国大陆区域 IP 地址。"},{"name":"yt-download","code":"ytdownload","enable":false,"note":"似乎不能使用。"},{"name":"YouTube（通过 youtube-dl）","code":"youtubedl","enable":true,"note":"需要自行安装 youtube-dl。"},{"name":"YouTube（通过 yt-dlp）","code":"ytdlp","enable":true,"note":"需要自行安装 yt-dlp（youtube-dl 仍在活跃维护的 fork）。"},{"name":"B 站音乐","code":"bilibili","enable":true},{"name":"第三方网易云 API","code":"pyncmd","enable":false}],"qq-cookie":"","migu-cookie":"","port":15579,"selectedVersion":null}`

已确认：
1. 环境变量正常且文件夹定位于C盘根目录
2. 尝试使用 https://github.com/ReviveUnblockNCMInstaller/RevivedUnblockInstaller/issues/21#issuecomment-1732312175 所提供的config 和 服务器文件，仍没有插件配置界面，且服务未启动
3. 尝试过使用全局VPN，无果
4. 使用过旧版本，可能有版本更新残留问题

**Comment by ihaveanissue1** [comment]
我尝试使用那个帖子的comfig和服务器文件后，可以听，但是音频播放出来是让我开通QQ会员..

**Comment by choumoxinpoi** [comment]
同问，遇到一样的问题，我也尝试用那个帖子的config和服务器,但是依然无法解灰（音源无法替换，但是能解除海外限制），然后配置界面显示空白

**Comment by hosts765614407** [comment]
我服务启动成功了，但是配置界面也是显示空白，音频播放出来也是让我开通会员....

**Comment by xygb233** [comment]
说不定律师函了

**Comment by zhangaceof** [comment]
+1111111111111

**Comment by MicroCBer** [comment]
duplicated with #36
