### ISSUE TITLE
无法启动服务

### ISSUE THREAD

**Issue by xingguangworld** [ReviveUnblockNCMInstaller/RevivedUnblockInstaller#39]
安装完成后，点击已禁用，显示正在启动服务，右上角报错未选中版本，无法正常使用
![report](https://github.com/ReviveUnblockNCMInstaller/RevivedUnblockInstaller/assets/47212355/8ae2a93a-573b-4b34-9c0d-a055a04e5bab)

**Comment by xingguangworld** [comment]
已安装revivedsource 仍无法使用

**Comment by zhangaceof** [comment]
还是不能用

**Comment by zhangaceof** [comment]
![{F4531FED-1E5C-4290-9C7F-62C0EFB1B18A}](https://github.com/ReviveUnblockNCMInstaller/RevivedUnblockInstaller/assets/40111336/edf5b83f-5dbb-4d77-a028-30ac7bb8dd71)
![{73940282-FE01-49bb-B7F4-CACBC72C8A62}](https://github.com/ReviveUnblockNCMInstaller/RevivedUnblockInstaller/assets/40111336/fb7b3d63-228e-4982-99ff-07465eb6d12b)
![{407EB90F-D0A6-481b-92F6-FCCD5507EA7A}](https://github.com/ReviveUnblockNCMInstaller/RevivedUnblockInstaller/assets/40111336/db28c9c9-e6e4-4d9a-bcf8-e2eb580675d2)
![{B944EA21-B6CD-40b3-8237-D21221AEDDDB}](https://github.com/ReviveUnblockNCMInstaller/RevivedUnblockInstaller/assets/40111336/eff087a7-8e87-4caa-b314-85868d75491c)

**Comment by zhangaceof** [comment]
显示是1.1.2  安装完是1.1.1 更新还是1.1.1 依旧空白

**Comment by zhangaceof** [comment]
@ReviveUnblockNCMInstaller

**Comment by zhangaceof** [comment]
+1

**Comment by zhangaceof** [comment]
我尝试卸载网易云音乐 删除c盘下betterncm文件夹 重新安装  依旧无效

**Comment by zhangaceof** [comment]
然后在多次重启网易云之后 网易云自动更新到了beta版本 不知道两者是否有关联

**Comment by zhangaceof** [comment]
然后在自动更新到beta版之后 我又手动安装了NeteaseCloudMusic_Music_official_2
.10.12.201849_32.exe  这个版本安装完之后，打开betterncm 又可以正常使用了

![{D7F35C73-F9D7-4a3b-B2E1-681A90855877}](https://github.com/ReviveUnblockNCMInstaller/RevivedUnblockInstaller/assets/40111336/95e351da-158a-4d54-b793-f3a4f4c235db)

**Comment by zhangaceof** [comment]
> 这个问题我刚才解决了，可能我是蒙的，操作步骤如下： 完全卸载网易云（用的GeekUninstaller），手动找到删除网易云安装目录所有的文件，删除C:\betterncm你的文件夹，最后重新安装网易云和插件，在安装解灰插件之前要开启系统代理或者tun模式，然后在下载完文件后，会弹出一个授权nodejs联网的窗口，这里要点击确定给予联网权限，后面就成功启动了。

你这个应该是对的

**Comment by xingguangworld** [comment]
> 你这个问题我刚才解决掉了，可能我是蒙的，操作步骤如下： 完全卸载网易云（用的GeekUninstaller），手动查找删除网易云安装目录所有的文件，删除C:\betterncm的文件夹，最后重新安装网易云和插件，在安装解灰插件之前要开启系统代理或者tun模式，然后在下载完文件后，会弹出一个授权nodejs联网的窗口，这里要点击确定给予联网权限，后面就成功启动了。

已解决 感谢帮助
