### ISSUE TITLE
0.27.3 以上版本无法启动

### ISSUE THREAD

**Issue by xietian19981121** [ReviveUnblockNCMInstaller/RevivedUnblockInstaller#43]
0.27.3 以前的版本是可以用的

![image](https://github.com/ReviveUnblockNCMInstaller/RevivedUnblockInstaller/assets/31039775/a42d7f25-0515-4f1e-bd00-98fd7c9dfe1c)

但是0.27.4 和 0.27.5 就会启动失败

![image](https://github.com/ReviveUnblockNCMInstaller/RevivedUnblockInstaller/assets/31039775/e52afdcf-1ffd-4b18-81c8-43ab9eeef433)

**Comment by xyh24921808** [comment]
我也是 相同的问题

**Comment by xyh24921808** [comment]
> 0.27.3 以前的版本是可以用的
> 
> ![图像](https://private-user-images.githubusercontent.com/31039775/311491798-a42d7f25-0515-4f1e-bd00-98fd7c9dfe1c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE3ODk2MDIsIm5iZiI6MTcxMTc4OTMwMiwicGF0aCI6Ii8zMTAzOTc3NS8zMTE0OTE3OTgtYTQyZDdmMjUtMDUxNS00ZjFlLWJkMDAtOThmZDdjOWRmZTFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzMwVDA5MDE0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY0NjRhOGJmMTFmNmRhZTc5MjI5MzhmYTRiZmMxOWRkMzJmYjhhZWNjMjhhYzI0MDllNzVmYjg2M2YyYThjZjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EwoZZWZKk1NNBwwt8X23eOIfoXIY0I4-2h05WdyFbK4)
> 
> 但是0.27.4 和 0.27.5 就会启动失败
> 
> ![图像](https://private-user-images.githubusercontent.com/31039775/311491836-e52afdcf-1ffd-4b18-81c8-43ab9eeef433.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE3ODk2MDIsIm5iZiI6MTcxMTc4OTMwMiwicGF0aCI6Ii8zMTAzOTc3NS8zMTE0OTE4MzYtZTUyYWZkY2YtMWZmZC00YjE4LTgxYzgtNDNhYjllZWVmNDMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzMwVDA5MDE0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM1NGY4YzczNTdlNDAwYTRlN2EzYjMyNTVkY2I4YjMwM2RhY2ZkMDdhODUzNzNlZTU3NTEyNThlMGFmM2U2M2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Tmjb2vYSXDAS8Bjz6mXaSxriAFkb35xm9bgWeBje7e0)

有办法了 把新版运行配置 的音源选少一点 或者之选几个就行了

**Comment by xietian19981121** [comment]
> > 0.27.3 以前的版本是可以用的
> > ![图像](https://private-user-images.githubusercontent.com/31039775/311491798-a42d7f25-0515-4f1e-bd00-98fd7c9dfe1c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE3ODk2MDIsIm5iZiI6MTcxMTc4OTMwMiwicGF0aCI6Ii8zMTAzOTc3NS8zMTE0OTE3OTgtYTQyZDdmMjUtMDUxNS00ZjFlLWJkMDAtOThmZDdjOWRmZTFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzMwVDA5MDE0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY0NjRhOGJmMTFmNmRhZTc5MjI5MzhmYTRiZmMxOWRkMzJmYjhhZWNjMjhhYzI0MDllNzVmYjg2M2YyYThjZjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EwoZZWZKk1NNBwwt8X23eOIfoXIY0I4-2h05WdyFbK4)
> > 但是0.27.4 和 0.27.5 就会启动失败
> > ![图像](https://private-user-images.githubusercontent.com/31039775/311491836-e52afdcf-1ffd-4b18-81c8-43ab9eeef433.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE3ODk2MDIsIm5iZiI6MTcxMTc4OTMwMiwicGF0aCI6Ii8zMTAzOTc3NS8zMTE0OTE4MzYtZTUyYWZkY2YtMWZmZC00YjE4LTgxYzgtNDNhYjllZWVmNDMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzMwVDA5MDE0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM1NGY4YzczNTdlNDAwYTRlN2EzYjMyNTVkY2I4YjMwM2RhY2ZkMDdhODUzNzNlZTU3NTEyNThlMGFmM2U2M2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Tmjb2vYSXDAS8Bjz6mXaSxriAFkb35xm9bgWeBje7e0)
> 
> 有办法了 把新版运行配置 的音源选少一点 或者之选几个就行了

但是很奇怪啊，以前的版本不会的 ...

**Comment by sktkyo** [comment]
现在0.27.8版本可以了，但是要在网易云客户端2.10.13下才行，3.0以上不可以。

**Comment by Fijil6** [comment]
音源选少一点真的有用！

**Comment by sktkyo** [comment]
> > [64#](https://github.com/ReviveUnblockNCMInstaller/RevivedUnblockInstaller/issues/64)说了，在V0.28.0版本 yt-download音源会导致无法启动
> 
> 是 [#63](https://github.com/ReviveUnblockNCMInstaller/RevivedUnblockInstaller/issues/63)

好的，了解，但这样一来，海外IP就真没有办法替换音乐库运行了。
