### ISSUE TITLE
版本适配请求

### ISSUE THREAD

**Issue by CapitalGrin** [ReviveUnblockNCMInstaller/RevivedUnblockInstaller#47]
网易开始强制推送3.0.0 beta版本，目前BetterNCM 1.3.2正常安装，但管理器显示Revive版本不匹配且无法正常安装。
烦请知悉，着手开始版本适配。

![image](https://github.com/ReviveUnblockNCMInstaller/RevivedUnblockInstaller/assets/109933411/304902da-c628-4058-8424-0d645df2d34f)
下图，需要打开不兼容版本才能看到Revive，安装不成功

**Comment by BoBppy** [comment]
应该要加一个ncm3-compatible": true

**Comment by sktkyo** [comment]
> 应该要加一个ncm3-compatible": true

这个要在哪里加？
