### ISSUE TITLE
酷我音乐音源无法使用，解灰项目无法使用

### ISSUE THREAD

**Issue by BYH404** [ReviveUnblockNCMInstaller/RevivedUnblockInstaller#50]
音频为“你所播放的内容需开通会员后畅听，如你是会员请到应用商店更新最新版本”。
最新版的解灰项目：https://github.com/UnblockNeteaseMusic/server 也出现了这个问题

**Comment by wuctrl** [comment]
我的所有音源全都会出现这种播放vip歌曲会变成6秒的“你所播放的内容需开通会员后畅听，如你是会员请到应用商店更新最新版本”。音频，大佬有解决的办法吗
![Annotation 2024-07-20 013003](https://github.com/user-attachments/assets/0abb2032-ac88-422d-a0f8-7d8540e88066)

**Comment by BYH404** [comment]
> 我的所有音源全都会出现这种播放vip歌曲会变成6秒的“你所播放的内容需开通会员后畅听，如你是会员请到应用商店更新最新版本”。音频，大佬有解决的办法吗 ![Annotation 2024-07-20 013003](https://private-user-images.githubusercontent.com/106809229/350502967-0abb2032-ac88-422d-a0f8-7d8540e88066.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE0NzkyOTMsIm5iZiI6MTcyMTQ3ODk5MywicGF0aCI6Ii8xMDY4MDkyMjkvMzUwNTAyOTY3LTBhYmIyMDMyLWFjODgtNDIyZC1hMGY4LTdkODU0MGU4ODA2Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyMFQxMjM2MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYjE0ZjliYzQ2ZTdlZGJhM2E3MmE2MThjMzk4MWFjMDc5MmNkYzFkYzRkMmY3NDUwZDk3N2Y5MDJlYmY4YTY2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.q5Clfl7aT42Psk6IkhtArtjMBCDpHHCT-Fld5MeW6mo)

只能等更新了 不知道什么时候可以用

**Comment by Ayuyi** [comment]
文件是更新了，但是他的[Releases 28](https://github.com/UnblockNeteaseMusic/server/releases)
v0.27.7这里面的整合没更新，项目有更新，betterNCM里又不能修改源，betterncm文件夹里又没有源的文件位置，只能等他更新

**Comment by ReviveUnblockNCMInstaller** [comment]
请等待上游发版或手动更新二进制。

**Comment by BYH404** [comment]
> 请等待上游发版或手动更新二进制。

如何手动更新？
