### ISSUE TITLE
希望添加个音源排序的功能

### ISSUE THREAD

**Issue by Whuihuan** [ReviveUnblockNCMInstaller/RevivedUnblockInstaller#6]
有时候部分音源匹配会变成翻唱，匹配程度较差，希望有个优先级排序，这样匹配差的就放后面

**Comment by ReviveUnblockNCMInstaller** [comment]
之前本来是打算做的，但是网易云 cef 的 Web Drag API 有点问题，以及本体不是严格匹配的，就放弃了。

**Comment by ReviveUnblockNCMInstaller** [comment]
可以把 B 站关掉，我这边测试着效果就还可以了。
