### ISSUE TITLE
打开的时候始终显示CMD窗口

### ISSUE THREAD

**Issue by cdwc233** [ReviveUnblockNCMInstaller/RevivedUnblockInstaller#8]
希望运行时隐藏cmd窗口，有点影响使用了
![QQ截图20230430153513](https://user-images.githubusercontent.com/54108192/235341496-ac1e41c5-d2ef-44cc-a66d-cf7866e8be93.png)

**Comment by ReviveUnblockNCMInstaller** [comment]
![image](https://user-images.githubusercontent.com/129636358/235342635-30a463f1-9cea-49cf-8346-8d5fe44e6010.png)

希望下次发 Issue 可以先看看已有功能……
