### ISSUE TITLE
设置里的自定义选项打不开

### ISSUE THREAD

**Issue by fbstorm** [ReviveUnblockNCMInstaller/RevivedUnblockInstaller#9]
https://user-images.githubusercontent.com/100028477/236500751-bef94e46-f89b-48a7-8f3c-b8f72f3eb9ad.mp4

**Comment by Healock** [comment]
+1

**Comment by ReviveUnblockNCMInstaller** [comment]
请见 [README.md](https://github.com/ReviveUnblockNCMInstaller/RevivedUnblockInstaller) 公告部分。

**Comment by windy1021** [comment]
问一下录屏软件和鼠标的那个黄色光圈是什么弄出来的

**Comment by fbstorm** [comment]
> 问一下录屏软件和鼠标的那个黄色光圈是什么弄出来的

这个是录屏软件自带的，叫“oCam”，设置里可以调出来这个效果
